Add dataDetectorTypes at textinput
rescript-react-native/rescript-react-native pull request #798
Opened 2023-03-21 03:28 UTC by Yummy-sk

A PR that adds dataDetectorTypes to textInput.

[dataDetectorTypes](https://reactnative.dev/docs/textinput#datadetectortypes-ios)

2023-03-21 04:18 UTC, mununki commented
I think binding to an array would be more scalable, what do you think? https://reactnative.dev/docs/textinput#datadetectortypes-ios:~:text=You%20can%20provide%20one%20type%20or%20an%20array%20of%20many%20types.

2023-03-21 05:16 UTC, Yummy-sk commented
> I think binding to an array would be more scalable, what do you think? https://reactnative.dev/docs/textinput#datadetectortypes-ios:~:text=You%20can%20provide%20one%20type%20or%20an%20array%20of%20many%20types.

Thanks! When I look at the types, I get the following, so I think it would be better to handle it as an array as you said.

```
dataDetectorTypes?: DataDetectorTypes | DataDetectorTypes[] | undefined;
```

2023-03-21 16:13 UTC, MoOx requested changes
I guess we could do it this way ?

2023-03-21 16:13 UTC, MoOx commented on src/components/TextInput.res
> +
```suggestion
```

2023-04-23 16:13 UTC, MoOx commented on src/components/TextInput.res
> +  ~dataDetectorTypes: array<Text.dataDetectorTypes>=?,
```suggestion
  ~dataDetectorTypes: array<Text.dataDetectorType>=?,
```

2023-04-23 16:15 UTC, MoOx approved these changes

2023-04-23 16:15 UTC, merged

2023-04-24 01:02 UTC, Yummy-sk commented
@MoOx  Sorry for the late reply, I think the implementation you suggested is better :)